---
Name: app
Before:
    - '*'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite

SilverStripe\Filesystem\Flysystem\FlysystemAssetStore:
  legacy_paths: true

SilverStripe\Assets\File:
  migrate_legacy_file: true
  allowed_extensions: 
    - pdf 
    - mp4
ElementalEditor:
  extensions:
    - CustomElementalEditor
SilverStripe\SAML\Authenticators\SAMLAuthenticator:
  name: "Hawk ID"